---
- hosts: kubernetes-worker-nodes
  vars_files:
  - env_variables
  tasks:
  - name: Copying token to worker nodes
    copy:
      src: "{{ token_file }}"
      dest: /tmp/join_token
      mode: '0644'

  - name: Joining worker nodes with Kubernetes master
    command: >
      sh -c "grep -i 'kubeadm join' /tmp/join_token | sh"
    args:
      executable: /bin/bash
