---
- hosts: all
  vars_files:
    - env_variables
  tasks:
    - name: Ensure gpg is installed
      apt:
        name: gnupg
        state: present
        update_cache: yes

    - name: Add Kubernetes APT repository key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Add Kubernetes APT repository
      apt_repository:
        repo: "deb https://apt.kubernetes.io/ kubernetes-bionic main"
        state: present

    - name: Clean APT cache
      apt:
        autoclean: yes
        update_cache: yes

    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Installing required packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop: "{{ packages }}"

    - name: Starting and Enabling the required services
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop: "{{ services }}"

    - name: Allow Network Ports in UFW
      ufw:
        rule: allow
        name: "{{ item }}"
        state: enabled
      loop: "{{ ports }}"

    - name: Enabling Bridge Firewall Rule
      sysctl:
        name: net.bridge.bridge-nf-call-iptables
        value: 1
        state: present
        reload: yes
